ci: Preload existing test images from text-overhaul-figures branch
This allows checking that there are no _new_ failures, without
committing the new figures to the repo until the branch is complete.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -95,6 +95,25 @@ jobs:
           fetch-depth: 0
           persist-credentials: false
 
+      - name: Preload test images
+        run: |
+          git config --global user.name 'Matplotlib'
+          git config --global user.email 'nobody@matplotlib.org'
+          git fetch https://github.com/QuLogic/matplotlib.git text-overhaul-figures:text-overhaul-figures
+          git merge --no-commit text-overhaul-figures || true
+          # If there are any conflicts in baseline images, then pick "ours",
+          # which should be the updated images in the PR.
+          conflicts=$(git diff --name-only --diff-filter=U \
+                      lib/matplotlib/tests/baseline_images \
+                      lib/mpl_toolkits/*/tests/baseline_images)
+          if [ -n "${conflicts}" ]; then
+            git checkout --ours -- "${conflicts}"
+            git add -- "${conflicts}"
+          fi
+          # If committing fails, there were conflicts other than the baseline images,
+          # which should not be allowed to happen, and should fail the build.
+          git commit -m 'Preload test images from branch text-overhaul-figures'
+
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
         with:
